name: CI/CD Pipeline for Sensible Health Application

on:
  push:
    branches:
      - main

env:
  REGISTRY: dockerhub.io
  IMAGE_NAME: mullickzaidkhanjb/chatn8n:latest

jobs:
  build-and-publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}

  deploy:
    name: Deploy Image in Remote VPS
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: SSH into WildFly server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          command_timeout: 30m
          script: |
            cd /var/www/NextJS/Sensible-Health-JR
            docker pull ${{ env.IMAGE_NAME }}
            docker-compose down
            docker-compose up -d
